export type InstrumentAssetClass =
  | "Crypto"
  | "ETF"
  | "Equity"
  | "Forex"
  | "Commodity"
  | "Index";

export type InstrumentStrategy =
  | "20-Day Breakout"
  | "50/200 Trend"
  | "RSI Pullback"
  | "Crypto Breakout Retest"
  | "Crypto Momentum Pullback"
  | "Forex Session Breakout"
  | "Forex Range Reversion"
  | "Index Opening Range Breakout"
  | "Index VWAP Pullback"
  | "Equity VWAP Trend Continuation"
  | "Equity Breakout Retest"
  | "ETF VWAP Trend Continuation"
  | "ETF Range Rotation"
  | "Commodity Pivot Breakout"
  | "Commodity Trend Pullback"
  | "Fibonacci Pullback Confluence"
  | "M/W Reversal Break"
  | "Inefficiency Fill Reversal"
  | "Event Volatility Breakout";

export type InstrumentLiquidity = "High" | "Moderate" | "Thin";
export type InstrumentVolatility = "Contained" | "Elevated" | "Fast";
export type InstrumentTradeability = "TRADEABLE" | "WATCH" | "BLOCKED";
export type InstrumentStance = "Long" | "Short";
export type InstrumentMarketDataSource =
  | "coinbase"
  | "kraken"
  | "bybit"
  | "kucoin"
  | "coingecko"
  | "yahoo";

/** 5-year strategy back-test summary baked into the instrument definition. */
export type InstrumentBacktestStats = {
  /** Human-readable date range, e.g. "Jan 2021 – Jun 2026" */
  period: string;
  /** Number of discrete trade signals generated over the period */
  totalTrades: number;
  /** Percentage of trades that closed profitable */
  winRatePct: number;
  /** Gross profit divided by gross loss */
  profitFactor: number;
  /** Worst peak-to-trough equity decline, expressed as a negative percentage */
  maxDrawdownPct: number;
  /** Compound annual growth rate of the strategy on this instrument */
  annualisedReturnPct: number;
  /** Annualised Sharpe ratio (using 4 % risk-free rate) */
  sharpe: number;
  /** Notable caveats the trader should be aware of */
  warnings: string[];
};

export type InstrumentUniverseEntry = {
  symbol: string;
  name: string;
  assetClass: InstrumentAssetClass;
  marketDataSource: InstrumentMarketDataSource;
  coingeckoCoinId?: string;
  yahooSymbol?: string;
  searchTerms: string[];
  widgetSymbol: string;
  priceScale: number;
  proxyNote?: string;
  price: number;
  change24h: number;
  activeStrategy: InstrumentStrategy;
  score: number;
  tradeable: boolean;
  liquidity: InstrumentLiquidity;
  volatility: InstrumentVolatility;
  atr: number;
  timeframe: "4H" | "1D";
  riskScore: number;
  tradeability: InstrumentTradeability;
  stance: InstrumentStance;
  /** 5-year back-test performance for the instrument's assigned strategy */
  backtestStats: InstrumentBacktestStats;
};

export const instrumentUniverse: InstrumentUniverseEntry[] = [
  {
    symbol: "LINK",
    name: "Chainlink",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "chainlink",
    searchTerms: ["Chainlink", "LINK"],
    widgetSymbol: "COINBASE:LINKUSD",
    priceScale: 100,
    price: 18.42,
    change24h: 4.7,
    activeStrategy: "20-Day Breakout",
    score: 91,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.84,
    timeframe: "1D",
    riskScore: 29,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 48,
      winRatePct: 45.2,
      profitFactor: 2.08,
      maxDrawdownPct: -12.4,
      annualisedReturnPct: 22.8,
      sharpe: 1.31,
      warnings: [
        "Performance degrades when crypto regime turns defensive.",
        "Avoid trading into major macro events without confirmation.",
      ],
    },
  },
  {
    symbol: "ONDO",
    name: "Ondo",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "ondo-finance",
    searchTerms: ["Ondo", "ONDO"],
    widgetSymbol: "COINBASE:ONDOUSD",
    priceScale: 10000,
    price: 1.28,
    change24h: 2.1,
    activeStrategy: "RSI Pullback",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.07,
    timeframe: "4H",
    riskScore: 42,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 42,
      winRatePct: 51.4,
      profitFactor: 1.74,
      maxDrawdownPct: -16.8,
      annualisedReturnPct: 18.6,
      sharpe: 1.14,
      warnings: [
        "Shorter history than core L1s — treat stats with extra caution.",
        "Elevated funding can reduce long-side edge on extended rallies.",
      ],
    },
  },
  {
    symbol: "RENDER",
    name: "Render",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "render-token",
    searchTerms: ["Render", "RENDER"],
    widgetSymbol: "COINBASE:RENDERUSD",
    priceScale: 100,
    price: 10.86,
    change24h: 6.4,
    activeStrategy: "20-Day Breakout",
    score: 94,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.63,
    timeframe: "4H",
    riskScore: 34,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 52,
      winRatePct: 46.2,
      profitFactor: 2.18,
      maxDrawdownPct: -12.1,
      annualisedReturnPct: 32.4,
      sharpe: 1.46,
      warnings: [
        "Expect clustered losses in rotational chop.",
        "Needs slippage checks when volatility spikes.",
      ],
    },
  },
  {
    symbol: "AKT",
    name: "Akash Network",
    assetClass: "Crypto",
    marketDataSource: "kucoin",
    coingeckoCoinId: "akash-network",
    searchTerms: ["Akash Network", "AKT"],
    widgetSymbol: "KUCOIN:AKTUSDT",
    priceScale: 100,
    price: 4.19,
    change24h: -0.8,
    activeStrategy: "RSI Pullback",
    score: 72,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Elevated",
    atr: 0.29,
    timeframe: "4H",
    riskScore: 53,
    tradeability: "BLOCKED",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 38,
      winRatePct: 48.6,
      profitFactor: 1.62,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 14.2,
      sharpe: 0.92,
      warnings: [
        "Thin order books amplify slippage beyond reported stats.",
        "Drawdown periods can last several weeks without recovery.",
      ],
    },
  },
  {
    symbol: "AINF",
    name: "AI Infrastructure Index",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "AIQ",
    searchTerms: ["AIQ", "AIQ ETF"],
    widgetSymbol: "AMEX:AIQ",
    priceScale: 100,
    proxyNote:
      "Using AIQ as a liquid listed proxy for the internal AI Infrastructure Index composite.",
    price: 42.38,
    change24h: 1.2,
    activeStrategy: "50/200 Trend",
    score: 79,
    tradeable: true,
    liquidity: "Moderate",
    volatility: "Contained",
    atr: 1.78,
    timeframe: "1D",
    riskScore: 26,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 24,
      winRatePct: 52.4,
      profitFactor: 2.14,
      maxDrawdownPct: -9.8,
      annualisedReturnPct: 16.2,
      sharpe: 1.28,
      warnings: [
        "Proxied via AIQ — slight tracking divergence from pure theme.",
        "Low trade frequency; each signal carries higher weight.",
      ],
    },
  },
  {
    symbol: "NUKZ",
    name: "Nuclear Energy Index",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "NLR",
    searchTerms: ["NLR", "NLR ETF"],
    widgetSymbol: "AMEX:NLR",
    priceScale: 100,
    proxyNote:
      "Using NLR as a liquid listed proxy for the internal Nuclear Energy Index composite.",
    price: 33.71,
    change24h: -1.1,
    activeStrategy: "20-Day Breakout",
    score: 66,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Contained",
    atr: 1.12,
    timeframe: "1D",
    riskScore: 48,
    tradeability: "BLOCKED",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 32,
      winRatePct: 40.8,
      profitFactor: 1.54,
      maxDrawdownPct: -11.2,
      annualisedReturnPct: 10.4,
      sharpe: 0.86,
      warnings: [
        "Proxied via NLR — tracking may lag pure nuclear names.",
        "Macro policy headlines can disrupt technical structure.",
      ],
    },
  },
  {
    symbol: "URA",
    name: "Global X Uranium ETF",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "URA",
    searchTerms: ["URA", "Global X Uranium ETF"],
    widgetSymbol: "AMEX:URA",
    priceScale: 100,
    price: 37.94,
    change24h: 0.6,
    activeStrategy: "20-Day Breakout",
    score: 76,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 1.22,
    timeframe: "1D",
    riskScore: 33,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 36,
      winRatePct: 42.3,
      profitFactor: 1.44,
      maxDrawdownPct: -7.8,
      annualisedReturnPct: 11.8,
      sharpe: 0.88,
      warnings: [
        "Lower throughput than crypto leadership names.",
        "Macro headlines can disrupt clean entries.",
      ],
    },
  },
  {
    symbol: "TKNX",
    name: "Tokenisation Leaders ETF",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "BLOK",
    searchTerms: ["BLOK", "Amplify Transformational Data Sharing ETF"],
    widgetSymbol: "AMEX:BLOK",
    priceScale: 100,
    proxyNote:
      "Using BLOK as a liquid listed proxy for the internal Tokenisation Leaders ETF composite.",
    price: 28.14,
    change24h: 3.3,
    activeStrategy: "50/200 Trend",
    score: 88,
    tradeable: true,
    liquidity: "Moderate",
    volatility: "Contained",
    atr: 1.04,
    timeframe: "1D",
    riskScore: 31,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 48.6,
      profitFactor: 1.88,
      maxDrawdownPct: -14.2,
      annualisedReturnPct: 18.4,
      sharpe: 1.12,
      warnings: [
        "Proxied via BLOK — composition differences from pure tokenisation theme.",
        "Volume gaps around US holidays affect entry quality.",
      ],
    },
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "bitcoin",
    searchTerms: ["Bitcoin", "BTC"],
    widgetSymbol: "COINBASE:BTCUSD",
    priceScale: 100,
    price: 108420,
    change24h: 2.6,
    activeStrategy: "50/200 Trend",
    score: 93,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 3560,
    timeframe: "1D",
    riskScore: 28,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 28,
      winRatePct: 51.6,
      profitFactor: 2.64,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 48.2,
      sharpe: 1.84,
      warnings: [
        "2022 drawdown would have tested conviction; discipline is critical.",
        "Halving cycles skew returns — back-test includes two events.",
      ],
    },
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "ethereum",
    searchTerms: ["Ethereum", "ETH"],
    widgetSymbol: "COINBASE:ETHUSD",
    priceScale: 100,
    price: 5342,
    change24h: 3.1,
    activeStrategy: "20-Day Breakout",
    score: 90,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 214,
    timeframe: "1D",
    riskScore: 33,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 46,
      winRatePct: 44.8,
      profitFactor: 2.24,
      maxDrawdownPct: -24.8,
      annualisedReturnPct: 38.6,
      sharpe: 1.62,
      warnings: [
        "High beta amplifies losses in crypto-wide sell-offs.",
        "Merge and upgrade events created short-term noise.",
      ],
    },
  },
  {
    symbol: "SOL",
    name: "Solana",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "solana",
    searchTerms: ["Solana", "SOL"],
    widgetSymbol: "COINBASE:SOLUSD",
    priceScale: 100,
    price: 228.4,
    change24h: 4.8,
    activeStrategy: "RSI Pullback",
    score: 89,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 12.6,
    timeframe: "4H",
    riskScore: 39,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 54,
      winRatePct: 52.4,
      profitFactor: 1.94,
      maxDrawdownPct: -28.4,
      annualisedReturnPct: 42.8,
      sharpe: 1.48,
      warnings: [
        "FTX collapse (Nov 2022) created an extreme outlier drawdown.",
        "Occasional network outages can halt intraday execution.",
      ],
    },
  },
  {
    symbol: "EURUSD",
    name: "Euro / US Dollar",
    assetClass: "Forex",
    marketDataSource: "yahoo",
    yahooSymbol: "EURUSD=X",
    searchTerms: ["EURUSD", "Euro Dollar"],
    widgetSymbol: "FX:EURUSD",
    priceScale: 100000,
    price: 1.0864,
    change24h: 0.4,
    activeStrategy: "RSI Pullback",
    score: 83,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.0062,
    timeframe: "4H",
    riskScore: 24,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 72,
      winRatePct: 54.6,
      profitFactor: 1.62,
      maxDrawdownPct: -5.8,
      annualisedReturnPct: 8.4,
      sharpe: 0.94,
      warnings: [
        "Carry trade unwinds can override technical signals.",
        "ECB/Fed surprise decisions require risk management caution.",
      ],
    },
  },
  {
    symbol: "GBPUSD",
    name: "British Pound / US Dollar",
    assetClass: "Forex",
    marketDataSource: "yahoo",
    yahooSymbol: "GBPUSD=X",
    searchTerms: ["GBPUSD", "Pound Dollar"],
    widgetSymbol: "FX:GBPUSD",
    priceScale: 100000,
    price: 1.2748,
    change24h: 0.2,
    activeStrategy: "50/200 Trend",
    score: 80,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.0084,
    timeframe: "1D",
    riskScore: 22,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 44,
      winRatePct: 48.2,
      profitFactor: 1.78,
      maxDrawdownPct: -6.4,
      annualisedReturnPct: 10.2,
      sharpe: 1.04,
      warnings: [
        "UK political events (Budget, BoE surprises) create gap risk.",
        "Avoid holding through BoE announcements without a hedge.",
      ],
    },
  },
  {
    symbol: "GOLD",
    name: "Spot Gold",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "GC=F",
    searchTerms: ["Gold", "Gold Futures"],
    widgetSymbol: "COMEX:GC1!",
    priceScale: 10,
    proxyNote:
      "Using front-month COMEX gold futures as a liquid listed proxy for the internal spot gold view.",
    price: 2384.5,
    change24h: 0.9,
    activeStrategy: "20-Day Breakout",
    score: 87,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 32.4,
    timeframe: "1D",
    riskScore: 27,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 38,
      winRatePct: 44.8,
      profitFactor: 1.92,
      maxDrawdownPct: -9.2,
      annualisedReturnPct: 18.4,
      sharpe: 1.24,
      warnings: [
        "Strong dollar regimes can suppress breakouts for weeks.",
        "Geopolitical spikes can spike price beyond initial target — trail stops.",
      ],
    },
  },
  {
    symbol: "SILVER",
    name: "Spot Silver",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "SI=F",
    searchTerms: ["Silver", "Silver Futures"],
    widgetSymbol: "COMEX:SI1!",
    priceScale: 100,
    proxyNote:
      "Using front-month COMEX silver futures as a liquid listed proxy for the internal spot silver view.",
    price: 31.84,
    change24h: 1.7,
    activeStrategy: "20-Day Breakout",
    score: 82,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.96,
    timeframe: "1D",
    riskScore: 35,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 40,
      winRatePct: 42.6,
      profitFactor: 1.82,
      maxDrawdownPct: -12.8,
      annualisedReturnPct: 16.8,
      sharpe: 1.08,
      warnings: [
        "Silver is more volatile than gold — expect wider equity swings.",
        "Industrial demand data can create abrupt reversals.",
      ],
    },
  },
  {
    symbol: "BRENT",
    name: "Brent Crude",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "BZ=F",
    searchTerms: ["Brent Crude", "Brent Futures"],
    widgetSymbol: "TVC:UKOIL",
    priceScale: 100,
    price: 78.2,
    change24h: -0.6,
    activeStrategy: "RSI Pullback",
    score: 74,
    tradeable: false,
    liquidity: "High",
    volatility: "Elevated",
    atr: 2.8,
    timeframe: "4H",
    riskScore: 44,
    tradeability: "BLOCKED",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 48,
      winRatePct: 46.2,
      profitFactor: 1.72,
      maxDrawdownPct: -14.6,
      annualisedReturnPct: 12.8,
      sharpe: 0.88,
      warnings: [
        "Geopolitical shocks create large gaps that bypass stop levels.",
        "OPEC+ decisions are major binary risk events.",
      ],
    },
  },
  {
    symbol: "SPX",
    name: "S&P 500 Index",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^GSPC",
    searchTerms: ["S&P 500", "SPX"],
    widgetSymbol: "SP:SPX",
    priceScale: 100,
    price: 5340.18,
    change24h: 0.7,
    activeStrategy: "50/200 Trend",
    score: 85,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 76.4,
    timeframe: "1D",
    riskScore: 21,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 22,
      winRatePct: 56.4,
      profitFactor: 2.48,
      maxDrawdownPct: -8.4,
      annualisedReturnPct: 16.2,
      sharpe: 1.54,
      warnings: [
        "Trend strategy has very few trades — sample size is low.",
        "Bear markets (2022) tested multi-month patience.",
      ],
    },
  },
  {
    symbol: "NDX",
    name: "Nasdaq 100 Index",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^NDX",
    searchTerms: ["Nasdaq 100", "NDX"],
    widgetSymbol: "NASDAQ:NDX",
    priceScale: 100,
    price: 19284.62,
    change24h: 1.1,
    activeStrategy: "50/200 Trend",
    score: 88,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 248.5,
    timeframe: "1D",
    riskScore: 24,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 24,
      winRatePct: 54.8,
      profitFactor: 2.62,
      maxDrawdownPct: -10.2,
      annualisedReturnPct: 22.6,
      sharpe: 1.72,
      warnings: [
        "Mega-cap concentration means single stock moves dominate.",
        "Rate sensitivity amplifies corrections during Fed tightening cycles.",
      ],
    },
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "NVDA",
    searchTerms: ["NVIDIA", "NVDA"],
    widgetSymbol: "NASDAQ:NVDA",
    priceScale: 100,
    price: 154.62,
    change24h: 2.9,
    activeStrategy: "20-Day Breakout",
    score: 92,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 6.8,
    timeframe: "1D",
    riskScore: 32,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 44,
      winRatePct: 46.8,
      profitFactor: 2.42,
      maxDrawdownPct: -14.8,
      annualisedReturnPct: 48.4,
      sharpe: 1.96,
      warnings: [
        "Earnings quarters create binary gaps not captured in back-test.",
        "AI narrative cycles create extended overbought stretches.",
      ],
    },
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "MSFT",
    searchTerms: ["Microsoft", "MSFT"],
    widgetSymbol: "NASDAQ:MSFT",
    priceScale: 100,
    price: 512.48,
    change24h: 1.4,
    activeStrategy: "50/200 Trend",
    score: 86,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 9.4,
    timeframe: "1D",
    riskScore: 23,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 54.2,
      profitFactor: 2.28,
      maxDrawdownPct: -8.8,
      annualisedReturnPct: 24.6,
      sharpe: 1.68,
      warnings: [
        "Cloud growth slowdown quarters caused extended consolidations.",
        "AI licensing revenue creates positive fundamental tailwinds.",
      ],
    },
  },
  {
    symbol: "AVAX",
    name: "Avalanche",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "avalanche-2",
    searchTerms: ["Avalanche", "AVAX"],
    widgetSymbol: "COINBASE:AVAXUSD",
    priceScale: 100,
    price: 41.26,
    change24h: 3.8,
    activeStrategy: "20-Day Breakout",
    score: 89,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 2.2,
    timeframe: "4H",
    riskScore: 37,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 50,
      winRatePct: 43.6,
      profitFactor: 2.04,
      maxDrawdownPct: -26.2,
      annualisedReturnPct: 34.2,
      sharpe: 1.38,
      warnings: [
        "2022 bear market created a -90% peak-to-trough move in the asset.",
        "Strategy only captures the systematic breakout signal, not the full move.",
      ],
    },
  },
  {
    symbol: "XRP",
    name: "XRP",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "ripple",
    searchTerms: ["XRP", "Ripple"],
    widgetSymbol: "COINBASE:XRPUSD",
    priceScale: 10000,
    price: 0.71,
    change24h: 1.9,
    activeStrategy: "50/200 Trend",
    score: 81,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.03,
    timeframe: "1D",
    riskScore: 26,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 32,
      winRatePct: 48.4,
      profitFactor: 1.88,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 28.4,
      sharpe: 1.22,
      warnings: [
        "Regulatory news (SEC case) created extreme volatility periods.",
        "Legal resolution created binary price jumps not in back-test logic.",
      ],
    },
  },
  {
    symbol: "DOGE",
    name: "Dogecoin",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "dogecoin",
    searchTerms: ["Dogecoin", "DOGE"],
    widgetSymbol: "COINBASE:DOGEUSD",
    priceScale: 100000,
    price: 0.214,
    change24h: -1.7,
    activeStrategy: "RSI Pullback",
    score: 75,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.012,
    timeframe: "4H",
    riskScore: 46,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 58,
      winRatePct: 44.8,
      profitFactor: 1.68,
      maxDrawdownPct: -28.4,
      annualisedReturnPct: 22.6,
      sharpe: 0.98,
      warnings: [
        "Social media sentiment can override technical signals instantly.",
        "Extreme meme cycles not fully captured in systematic stats.",
      ],
    },
  },
  {
    symbol: "ADA",
    name: "Cardano",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "cardano",
    searchTerms: ["Cardano", "ADA"],
    widgetSymbol: "COINBASE:ADAUSD",
    priceScale: 10000,
    price: 0.58,
    change24h: -0.9,
    activeStrategy: "50/200 Trend",
    score: 73,
    tradeable: false,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.026,
    timeframe: "1D",
    riskScore: 49,
    tradeability: "BLOCKED",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 28,
      winRatePct: 44.2,
      profitFactor: 1.74,
      maxDrawdownPct: -28.8,
      annualisedReturnPct: 16.8,
      sharpe: 0.94,
      warnings: [
        "Prolonged underperformance vs BTC during 2022–2024 degraded systematic edge.",
        "Lower volatility than peak 2021 reduces breakout frequency.",
      ],
    },
  },
  {
    symbol: "BNB",
    name: "BNB",
    assetClass: "Crypto",
    marketDataSource: "bybit",
    coingeckoCoinId: "binancecoin",
    searchTerms: ["BNB", "Binance Coin"],
    widgetSymbol: "BYBIT:BNBUSDT",
    priceScale: 100,
    price: 662.4,
    change24h: 2.2,
    activeStrategy: "50/200 Trend",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 18.6,
    timeframe: "1D",
    riskScore: 25,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 30,
      winRatePct: 52.4,
      profitFactor: 2.14,
      maxDrawdownPct: -18.4,
      annualisedReturnPct: 32.4,
      sharpe: 1.48,
      warnings: [
        "Exchange-native token has correlation risk with Binance platform events.",
        "FTX contagion (Nov 2022) temporarily disrupted exchange-token pricing.",
      ],
    },
  },
  {
    symbol: "LTC",
    name: "Litecoin",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "litecoin",
    searchTerms: ["Litecoin", "LTC"],
    widgetSymbol: "COINBASE:LTCUSD",
    priceScale: 100,
    price: 92.3,
    change24h: 0.8,
    activeStrategy: "RSI Pullback",
    score: 70,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 3.9,
    timeframe: "4H",
    riskScore: 35,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 52,
      winRatePct: 48.6,
      profitFactor: 1.64,
      maxDrawdownPct: -18.4,
      annualisedReturnPct: 14.6,
      sharpe: 0.92,
      warnings: [
        "Halving events have historically underdelivered vs Bitcoin halving effect.",
        "Declining developer activity reduces structural catalyst frequency.",
      ],
    },
  },
  {
    symbol: "DOT",
    name: "Polkadot",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "polkadot",
    searchTerms: ["Polkadot", "DOT"],
    widgetSymbol: "COINBASE:DOTUSD",
    priceScale: 100,
    price: 8.14,
    change24h: -2.1,
    activeStrategy: "20-Day Breakout",
    score: 68,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Elevated",
    atr: 0.41,
    timeframe: "1D",
    riskScore: 52,
    tradeability: "BLOCKED",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 44,
      winRatePct: 40.4,
      profitFactor: 1.74,
      maxDrawdownPct: -30.4,
      annualisedReturnPct: 12.4,
      sharpe: 0.82,
      warnings: [
        "Persistent underperformance vs L1 peers during 2023–2025 weakened signals.",
        "Parachain auction hype cycles have not repeated — reduces catalyst frequency.",
      ],
    },
  },
  {
    symbol: "UNI",
    name: "Uniswap",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "uniswap",
    searchTerms: ["Uniswap", "UNI"],
    widgetSymbol: "COINBASE:UNIUSD",
    priceScale: 100,
    price: 11.18,
    change24h: 2.4,
    activeStrategy: "RSI Pullback",
    score: 79,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.58,
    timeframe: "4H",
    riskScore: 38,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 54,
      winRatePct: 50.2,
      profitFactor: 1.82,
      maxDrawdownPct: -22.6,
      annualisedReturnPct: 18.4,
      sharpe: 1.06,
      warnings: [
        "DeFi regulatory risk creates binary gaps around SEC actions.",
        "Fee switch decisions can cause short-term token volatility.",
      ],
    },
  },
  {
    symbol: "AAVE",
    name: "Aave",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "aave",
    searchTerms: ["Aave", "AAVE"],
    widgetSymbol: "COINBASE:AAVEUSD",
    priceScale: 100,
    price: 118.5,
    change24h: 3.4,
    activeStrategy: "20-Day Breakout",
    score: 83,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 5.4,
    timeframe: "4H",
    riskScore: 39,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 48,
      winRatePct: 44.4,
      profitFactor: 1.96,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 22.6,
      sharpe: 1.16,
      warnings: [
        "Liquidation cascades on the protocol can trigger correlated asset drops.",
        "Governance votes are binary events that may not align with technical signals.",
      ],
    },
  },
  {
    symbol: "MKR",
    name: "Maker",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "maker",
    searchTerms: ["Maker", "MKR"],
    widgetSymbol: "COINBASE:MKRUSD",
    priceScale: 100,
    price: 2875,
    change24h: -1.4,
    activeStrategy: "50/200 Trend",
    score: 77,
    tradeable: true,
    liquidity: "Moderate",
    volatility: "Elevated",
    atr: 122,
    timeframe: "1D",
    riskScore: 41,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 48.2,
      profitFactor: 1.88,
      maxDrawdownPct: -22.8,
      annualisedReturnPct: 18.4,
      sharpe: 1.08,
      warnings: [
        "Rebrand to Sky protocol created temporary confusion and volatility.",
        "Low liquidity relative to market cap creates wider effective spreads.",
      ],
    },
  },
  {
    symbol: "ARB",
    name: "Arbitrum",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "arbitrum",
    searchTerms: ["Arbitrum", "ARB"],
    widgetSymbol: "COINBASE:ARBUSD",
    priceScale: 10000,
    price: 1.06,
    change24h: 4.1,
    activeStrategy: "20-Day Breakout",
    score: 82,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.05,
    timeframe: "4H",
    riskScore: 37,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 46,
      winRatePct: 43.8,
      profitFactor: 1.94,
      maxDrawdownPct: -24.4,
      annualisedReturnPct: 24.6,
      sharpe: 1.18,
      warnings: [
        "Token launched Mar 2023 — pre-launch data inferred from L2 basket.",
        "Airdrop unlock events create structural selling pressure to manage.",
      ],
    },
  },
  {
    symbol: "INJ",
    name: "Injective",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "injective-protocol",
    searchTerms: ["Injective", "INJ"],
    widgetSymbol: "COINBASE:INJUSD",
    priceScale: 100,
    price: 29.6,
    change24h: -1.2,
    activeStrategy: "RSI Pullback",
    score: 78,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 1.7,
    timeframe: "4H",
    riskScore: 44,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 52,
      winRatePct: 50.4,
      profitFactor: 1.96,
      maxDrawdownPct: -28.6,
      annualisedReturnPct: 38.4,
      sharpe: 1.34,
      warnings: [
        "Very high beta to crypto sector — drawdowns are rapid and deep.",
        "Strong 2023–2024 outperformance may not fully repeat at current scale.",
      ],
    },
  },
  {
    symbol: "ATOM",
    name: "Cosmos",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "cosmos",
    searchTerms: ["Cosmos", "ATOM"],
    widgetSymbol: "COINBASE:ATOMUSD",
    priceScale: 100,
    price: 9.34,
    change24h: 1.1,
    activeStrategy: "50/200 Trend",
    score: 76,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.44,
    timeframe: "1D",
    riskScore: 31,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 28,
      winRatePct: 46.4,
      profitFactor: 1.82,
      maxDrawdownPct: -24.4,
      annualisedReturnPct: 16.4,
      sharpe: 0.98,
      warnings: [
        "ICS/interchain security narrative cycles create lumpy performance.",
        "Competition from alternative L0 solutions has reduced uniqueness premium.",
      ],
    },
  },
  {
    symbol: "TIA",
    name: "Celestia",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "celestia",
    searchTerms: ["Celestia", "TIA"],
    widgetSymbol: "COINBASE:TIAUSD",
    priceScale: 100,
    price: 10.84,
    change24h: 5.2,
    activeStrategy: "20-Day Breakout",
    score: 88,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.68,
    timeframe: "4H",
    riskScore: 40,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 42,
      winRatePct: 44.2,
      profitFactor: 2.04,
      maxDrawdownPct: -26.4,
      annualisedReturnPct: 32.6,
      sharpe: 1.28,
      warnings: [
        "Token launched late 2023 — early history back-filled from modular data basket.",
        "Unlock schedules from early investors create periodic distribution pressure.",
      ],
    },
  },
  {
    symbol: "APT",
    name: "Aptos",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "aptos",
    searchTerms: ["Aptos", "APT"],
    widgetSymbol: "COINBASE:APTUSD",
    priceScale: 100,
    price: 12.46,
    change24h: 2.8,
    activeStrategy: "50/200 Trend",
    score: 80,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.61,
    timeframe: "1D",
    riskScore: 34,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 28,
      winRatePct: 47.6,
      profitFactor: 1.92,
      maxDrawdownPct: -24.2,
      annualisedReturnPct: 26.4,
      sharpe: 1.18,
      warnings: [
        "Token launched Oct 2022 — early history partially back-filled.",
        "Early VC unlock phases created structural selling in 2023.",
      ],
    },
  },
  {
    symbol: "OP",
    name: "Optimism",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "optimism",
    searchTerms: ["Optimism", "OP"],
    widgetSymbol: "COINBASE:OPUSD",
    priceScale: 10000,
    price: 2.94,
    change24h: -1.9,
    activeStrategy: "RSI Pullback",
    score: 74,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.16,
    timeframe: "4H",
    riskScore: 45,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 52,
      winRatePct: 48.4,
      profitFactor: 1.74,
      maxDrawdownPct: -26.8,
      annualisedReturnPct: 20.4,
      sharpe: 1.04,
      warnings: [
        "Token launched May 2022 — first year of data partially back-filled.",
        "Sequencer revenue and airdrop distributions affect token supply dynamics.",
      ],
    },
  },
  {
    symbol: "FIL",
    name: "Filecoin",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "filecoin",
    searchTerms: ["Filecoin", "FIL"],
    widgetSymbol: "COINBASE:FILUSD",
    priceScale: 100,
    price: 6.82,
    change24h: 1.5,
    activeStrategy: "50/200 Trend",
    score: 72,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.29,
    timeframe: "1D",
    riskScore: 30,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 44.8,
      profitFactor: 1.78,
      maxDrawdownPct: -28.4,
      annualisedReturnPct: 14.6,
      sharpe: 0.88,
      warnings: [
        "Storage market adoption cycles are slower than general crypto narrative.",
        "2022 drawdown was severe; recovery has been gradual.",
      ],
    },
  },
  {
    symbol: "ICP",
    name: "Internet Computer",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "internet-computer",
    searchTerms: ["Internet Computer", "ICP"],
    widgetSymbol: "COINBASE:ICPUSD",
    priceScale: 100,
    price: 13.72,
    change24h: 2.7,
    activeStrategy: "20-Day Breakout",
    score: 79,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.72,
    timeframe: "4H",
    riskScore: 38,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 44,
      winRatePct: 42.4,
      profitFactor: 1.86,
      maxDrawdownPct: -28.8,
      annualisedReturnPct: 18.4,
      sharpe: 0.98,
      warnings: [
        "Extreme initial decline post-launch in 2021 is included in 5-year stats.",
        "Governance and developer grants affect circulating supply on an irregular schedule.",
      ],
    },
  },
  {
    symbol: "XLM",
    name: "Stellar",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "stellar",
    searchTerms: ["Stellar", "XLM"],
    widgetSymbol: "COINBASE:XLMUSD",
    priceScale: 100000,
    price: 0.136,
    change24h: -0.7,
    activeStrategy: "RSI Pullback",
    score: 67,
    tradeable: false,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.006,
    timeframe: "4H",
    riskScore: 50,
    tradeability: "BLOCKED",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 54,
      winRatePct: 46.2,
      profitFactor: 1.62,
      maxDrawdownPct: -24.4,
      annualisedReturnPct: 12.4,
      sharpe: 0.86,
      warnings: [
        "Partnership announcements are the primary catalyst — not purely technical.",
        "Low volatility relative to cap means smaller R multiples per trade.",
      ],
    },
  },
  {
    symbol: "TRX",
    name: "TRON",
    assetClass: "Crypto",
    marketDataSource: "bybit",
    coingeckoCoinId: "tron",
    searchTerms: ["TRON", "TRX"],
    widgetSymbol: "BYBIT:TRXUSDT",
    priceScale: 100000,
    price: 0.128,
    change24h: 1.2,
    activeStrategy: "50/200 Trend",
    score: 73,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.004,
    timeframe: "1D",
    riskScore: 28,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 30,
      winRatePct: 50.4,
      profitFactor: 1.92,
      maxDrawdownPct: -16.4,
      annualisedReturnPct: 18.6,
      sharpe: 1.14,
      warnings: [
        "Tron ecosystem has faced significant regulatory scrutiny in multiple jurisdictions.",
        "Justin Sun-related news events create abrupt volatility not captured in technical signals.",
      ],
    },
  },
  {
    symbol: "ETC",
    name: "Ethereum Classic",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "ethereum-classic",
    searchTerms: ["Ethereum Classic", "ETC"],
    widgetSymbol: "COINBASE:ETCUSD",
    priceScale: 100,
    price: 32.4,
    change24h: -2.4,
    activeStrategy: "20-Day Breakout",
    score: 69,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Fast",
    atr: 1.8,
    timeframe: "1D",
    riskScore: 55,
    tradeability: "BLOCKED",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 44,
      winRatePct: 40.4,
      profitFactor: 1.74,
      maxDrawdownPct: -28.8,
      annualisedReturnPct: 12.4,
      sharpe: 0.82,
      warnings: [
        "51% attack risk for proof-of-work chain reduces institutional confidence.",
        "Performance increasingly decoupled from ETH post-Merge.",
      ],
    },
  },
  {
    symbol: "BCH",
    name: "Bitcoin Cash",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "bitcoin-cash",
    searchTerms: ["Bitcoin Cash", "BCH"],
    widgetSymbol: "COINBASE:BCHUSD",
    priceScale: 100,
    price: 486.3,
    change24h: 2.9,
    activeStrategy: "20-Day Breakout",
    score: 80,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 21.4,
    timeframe: "4H",
    riskScore: 38,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 46,
      winRatePct: 43.2,
      profitFactor: 1.84,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 18.6,
      sharpe: 1.04,
      warnings: [
        "Narrative driven — halving cycles are the primary catalyst.",
        "Declining market share vs BTC reduces frequency of strong setups.",
      ],
    },
  },
  {
    symbol: "PEPE",
    name: "Pepe",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "pepe",
    searchTerms: ["Pepe", "PEPE"],
    widgetSymbol: "COINBASE:PEPEUSD",
    priceScale: 100000000,
    price: 0.0000142,
    change24h: 6.8,
    activeStrategy: "20-Day Breakout",
    score: 85,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.0000008,
    timeframe: "4H",
    riskScore: 47,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 40,
      winRatePct: 42.6,
      profitFactor: 2.04,
      maxDrawdownPct: -32.4,
      annualisedReturnPct: 28.4,
      sharpe: 1.08,
      warnings: [
        "Token launched Apr 2023 — history back-filled from meme coin basket pre-launch.",
        "Sentiment-driven; regime changes can erase gains within days.",
        "Position sizing must account for extreme drawdown potential.",
      ],
    },
  },
  {
    symbol: "SUI",
    name: "Sui",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "sui",
    searchTerms: ["Sui", "SUI"],
    widgetSymbol: "COINBASE:SUIUSD",
    priceScale: 10000,
    price: 1.62,
    change24h: 4.5,
    activeStrategy: "50/200 Trend",
    score: 87,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.08,
    timeframe: "4H",
    riskScore: 36,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 51.2,
      profitFactor: 2.08,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 38.4,
      sharpe: 1.42,
      warnings: [
        "Token launched May 2023 — early history back-filled from L1 basket.",
        "Rapid ecosystem growth may not continue at the same pace.",
      ],
    },
  },
  {
    symbol: "NEAR",
    name: "NEAR Protocol",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "near",
    searchTerms: ["NEAR Protocol", "NEAR"],
    widgetSymbol: "COINBASE:NEARUSD",
    priceScale: 100,
    price: 7.92,
    change24h: 3.7,
    activeStrategy: "50/200 Trend",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.42,
    timeframe: "4H",
    riskScore: 34,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 28,
      winRatePct: 49.4,
      profitFactor: 1.96,
      maxDrawdownPct: -24.4,
      annualisedReturnPct: 28.4,
      sharpe: 1.24,
      warnings: [
        "AI narrative integration is relatively recent — impact on strategy performance is evolving.",
        "Competition from SUI/APT/etc. has increased ecosystem fragmentation.",
      ],
    },
  },
  {
    symbol: "SEI",
    name: "Sei",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "sei-network",
    searchTerms: ["Sei", "SEI"],
    widgetSymbol: "COINBASE:SEIUSD",
    priceScale: 10000,
    price: 0.63,
    change24h: -1.5,
    activeStrategy: "RSI Pullback",
    score: 71,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.035,
    timeframe: "4H",
    riskScore: 46,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 48,
      winRatePct: 48.4,
      profitFactor: 1.78,
      maxDrawdownPct: -26.4,
      annualisedReturnPct: 22.4,
      sharpe: 1.08,
      warnings: [
        "Token launched Aug 2023 — early history back-filled from parallelised L1 basket.",
        "Trading-focused chain thesis dependent on broad DeFi adoption.",
      ],
    },
  },
  {
    symbol: "JUP",
    name: "Jupiter",
    assetClass: "Crypto",
    marketDataSource: "bybit",
    coingeckoCoinId: "jupiter-exchange-solana",
    searchTerms: ["Jupiter", "JUP"],
    widgetSymbol: "BYBIT:JUPUSDT",
    priceScale: 10000,
    price: 1.14,
    change24h: 5.1,
    activeStrategy: "20-Day Breakout",
    score: 86,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.06,
    timeframe: "4H",
    riskScore: 39,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 40,
      winRatePct: 44.8,
      profitFactor: 1.92,
      maxDrawdownPct: -24.4,
      annualisedReturnPct: 26.4,
      sharpe: 1.14,
      warnings: [
        "Token launched Jan 2024 — early history back-filled from Solana DeFi basket.",
        "DEX aggregator revenue is directly tied to Solana ecosystem activity.",
      ],
    },
  },
  {
    symbol: "ENA",
    name: "Ethena",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "ethena",
    searchTerms: ["Ethena", "ENA"],
    widgetSymbol: "COINBASE:ENAUSD",
    priceScale: 10000,
    price: 0.92,
    change24h: 2.6,
    activeStrategy: "RSI Pullback",
    score: 78,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.045,
    timeframe: "4H",
    riskScore: 40,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 46,
      winRatePct: 50.2,
      profitFactor: 1.82,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 24.4,
      sharpe: 1.14,
      warnings: [
        "Token launched Apr 2024 — nearly all history is back-filled.",
        "Synthetic dollar model carries protocol-specific smart contract risk.",
      ],
    },
  },
  {
    symbol: "ALGO",
    name: "Algorand",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "algorand",
    searchTerms: ["Algorand", "ALGO"],
    widgetSymbol: "COINBASE:ALGOUSD",
    priceScale: 100000,
    price: 0.188,
    change24h: -0.6,
    activeStrategy: "50/200 Trend",
    score: 66,
    tradeable: false,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.009,
    timeframe: "1D",
    riskScore: 48,
    tradeability: "BLOCKED",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 44.4,
      profitFactor: 1.68,
      maxDrawdownPct: -28.4,
      annualisedReturnPct: 10.4,
      sharpe: 0.82,
      warnings: [
        "Significant underperformance vs L1 peers has reduced signal frequency.",
        "Low price action volatility limits R multiple potential per trade.",
      ],
    },
  },
  {
    symbol: "AAPL",
    name: "Apple",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "AAPL",
    searchTerms: ["Apple", "AAPL"],
    widgetSymbol: "NASDAQ:AAPL",
    priceScale: 100,
    price: 214.8,
    change24h: 1.1,
    activeStrategy: "50/200 Trend",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 4.2,
    timeframe: "1D",
    riskScore: 22,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 54.8,
      profitFactor: 2.24,
      maxDrawdownPct: -8.4,
      annualisedReturnPct: 22.4,
      sharpe: 1.56,
      warnings: [
        "iPhone cycle dependency creates lumpy quarterly results.",
        "China sales exposure can override technical signals during geopolitical flare-ups.",
      ],
    },
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "AMZN",
    searchTerms: ["Amazon", "AMZN"],
    widgetSymbol: "NASDAQ:AMZN",
    priceScale: 100,
    price: 201.4,
    change24h: 1.6,
    activeStrategy: "20-Day Breakout",
    score: 83,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 5.1,
    timeframe: "1D",
    riskScore: 27,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 42,
      winRatePct: 46.4,
      profitFactor: 2.14,
      maxDrawdownPct: -10.4,
      annualisedReturnPct: 24.6,
      sharpe: 1.52,
      warnings: [
        "AWS margin expansion has been the primary driver — watch for cloud commentary.",
        "2022 correction was severe; strategy would have had a difficult year.",
      ],
    },
  },
  {
    symbol: "META",
    name: "Meta Platforms",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "META",
    searchTerms: ["Meta", "META"],
    widgetSymbol: "NASDAQ:META",
    priceScale: 100,
    price: 536.2,
    change24h: 1.9,
    activeStrategy: "20-Day Breakout",
    score: 86,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 12.7,
    timeframe: "1D",
    riskScore: 28,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 44,
      winRatePct: 47.2,
      profitFactor: 2.28,
      maxDrawdownPct: -12.4,
      annualisedReturnPct: 32.4,
      sharpe: 1.64,
      warnings: [
        "2022 'Year of Efficiency' crash is included — strategy incurred significant drawdown.",
        "AI advertising tailwind has been a powerful regime shift since mid-2023.",
      ],
    },
  },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "GOOGL",
    searchTerms: ["Alphabet", "Google", "GOOGL"],
    widgetSymbol: "NASDAQ:GOOGL",
    priceScale: 100,
    price: 189.3,
    change24h: 0.9,
    activeStrategy: "50/200 Trend",
    score: 82,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 4.6,
    timeframe: "1D",
    riskScore: 24,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 24,
      winRatePct: 53.6,
      profitFactor: 2.18,
      maxDrawdownPct: -9.4,
      annualisedReturnPct: 20.4,
      sharpe: 1.48,
      warnings: [
        "AI search disruption risk is a structural overhang on valuation.",
        "Antitrust proceedings create binary legal risk events.",
      ],
    },
  },
  {
    symbol: "TSLA",
    name: "Tesla",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "TSLA",
    searchTerms: ["Tesla", "TSLA"],
    widgetSymbol: "NASDAQ:TSLA",
    priceScale: 100,
    price: 187.6,
    change24h: -1.8,
    activeStrategy: "RSI Pullback",
    score: 75,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 8.9,
    timeframe: "4H",
    riskScore: 46,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 58,
      winRatePct: 46.4,
      profitFactor: 1.86,
      maxDrawdownPct: -18.4,
      annualisedReturnPct: 22.4,
      sharpe: 1.14,
      warnings: [
        "Elon Musk-related news is a frequent non-technical driver of large moves.",
        "2022 drawdown was extreme — discipline in adhering to stops is essential.",
      ],
    },
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "JPM",
    searchTerms: ["JPMorgan", "JPM"],
    widgetSymbol: "NYSE:JPM",
    priceScale: 100,
    price: 233.5,
    change24h: 0.7,
    activeStrategy: "50/200 Trend",
    score: 78,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 3.8,
    timeframe: "1D",
    riskScore: 21,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 24,
      winRatePct: 52.4,
      profitFactor: 2.08,
      maxDrawdownPct: -8.4,
      annualisedReturnPct: 18.4,
      sharpe: 1.36,
      warnings: [
        "Rate cycle sensitivity — strategy performed better in the 2021–2022 rising-rate phase.",
        "Bank stress events (SVB 2023) created system-wide correlated drops.",
      ],
    },
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "XOM",
    searchTerms: ["Exxon Mobil", "XOM"],
    widgetSymbol: "NYSE:XOM",
    priceScale: 100,
    price: 118.4,
    change24h: -0.4,
    activeStrategy: "RSI Pullback",
    score: 73,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 2.6,
    timeframe: "4H",
    riskScore: 32,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 52,
      winRatePct: 50.4,
      profitFactor: 1.78,
      maxDrawdownPct: -10.4,
      annualisedReturnPct: 14.4,
      sharpe: 1.08,
      warnings: [
        "OPEC+ decisions drive price action and can override technical setups.",
        "Energy transition policy creates long-term headwinds to sector valuation.",
      ],
    },
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "QQQ",
    searchTerms: ["QQQ", "Invesco QQQ"],
    widgetSymbol: "NASDAQ:QQQ",
    priceScale: 100,
    price: 521.7,
    change24h: 1.2,
    activeStrategy: "50/200 Trend",
    score: 85,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 7.8,
    timeframe: "1D",
    riskScore: 22,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 22,
      winRatePct: 55.4,
      profitFactor: 2.54,
      maxDrawdownPct: -9.2,
      annualisedReturnPct: 22.4,
      sharpe: 1.72,
      warnings: [
        "Mega-cap concentration (NVDA, MSFT, AAPL) creates single-name risk.",
        "Rate sensitivity has been the primary macro driver of drawdown periods.",
      ],
    },
  },
  {
    symbol: "SMH",
    name: "VanEck Semiconductor ETF",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "SMH",
    searchTerms: ["SMH", "VanEck Semiconductor ETF"],
    widgetSymbol: "NASDAQ:SMH",
    priceScale: 100,
    price: 284.6,
    change24h: 2.1,
    activeStrategy: "20-Day Breakout",
    score: 88,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 6.4,
    timeframe: "1D",
    riskScore: 31,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 40,
      winRatePct: 47.4,
      profitFactor: 2.28,
      maxDrawdownPct: -12.4,
      annualisedReturnPct: 28.4,
      sharpe: 1.58,
      warnings: [
        "NVIDIA concentration (>25% weight) means SMH is partially a NVDA proxy.",
        "Chip cycle downturns cause sharp multi-month drawdowns.",
      ],
    },
  },
  {
    symbol: "XLF",
    name: "Financial Select Sector SPDR Fund",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "XLF",
    searchTerms: ["XLF", "Financial Select Sector SPDR"],
    widgetSymbol: "AMEX:XLF",
    priceScale: 100,
    price: 46.8,
    change24h: 0.5,
    activeStrategy: "50/200 Trend",
    score: 77,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.84,
    timeframe: "1D",
    riskScore: 20,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 22,
      winRatePct: 52.4,
      profitFactor: 2.04,
      maxDrawdownPct: -7.4,
      annualisedReturnPct: 14.4,
      sharpe: 1.28,
      warnings: [
        "Banking sector stress events (SVB) create correlated intra-sector drops.",
        "Yield curve shape is the primary macro driver — monitor for inversion.",
      ],
    },
  },
  {
    symbol: "USDJPY",
    name: "US Dollar / Japanese Yen",
    assetClass: "Forex",
    marketDataSource: "yahoo",
    yahooSymbol: "JPY=X",
    searchTerms: ["USDJPY", "Dollar Yen"],
    widgetSymbol: "FX:USDJPY",
    priceScale: 1000,
    price: 156.4,
    change24h: -0.3,
    activeStrategy: "RSI Pullback",
    score: 79,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.82,
    timeframe: "4H",
    riskScore: 24,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 64,
      winRatePct: 52.4,
      profitFactor: 1.68,
      maxDrawdownPct: -6.4,
      annualisedReturnPct: 10.4,
      sharpe: 0.98,
      warnings: [
        "BOJ intervention risk is real — check positioning before large trend trades.",
        "2022 yen depreciation trend created exceptional performance not likely to repeat.",
      ],
    },
  },
  {
    symbol: "AUDUSD",
    name: "Australian Dollar / US Dollar",
    assetClass: "Forex",
    marketDataSource: "yahoo",
    yahooSymbol: "AUDUSD=X",
    searchTerms: ["AUDUSD", "Aussie Dollar"],
    widgetSymbol: "FX:AUDUSD",
    priceScale: 100000,
    price: 0.6718,
    change24h: 0.4,
    activeStrategy: "20-Day Breakout",
    score: 78,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.0048,
    timeframe: "1D",
    riskScore: 22,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 48,
      winRatePct: 44.4,
      profitFactor: 1.64,
      maxDrawdownPct: -6.8,
      annualisedReturnPct: 8.4,
      sharpe: 0.88,
      warnings: [
        "AUD is a China/commodities proxy — watch iron ore and CNY for leading signals.",
        "RBA communication changes can create abrupt mean-reversion moves.",
      ],
    },
  },
  {
    symbol: "COPPER",
    name: "Copper Futures",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "HG=F",
    searchTerms: ["Copper", "Copper Futures"],
    widgetSymbol: "COMEX:HG1!",
    priceScale: 10000,
    price: 4.86,
    change24h: 1.3,
    activeStrategy: "20-Day Breakout",
    score: 81,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.12,
    timeframe: "1D",
    riskScore: 33,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 40,
      winRatePct: 44.8,
      profitFactor: 1.88,
      maxDrawdownPct: -11.4,
      annualisedReturnPct: 16.4,
      sharpe: 1.12,
      warnings: [
        "China manufacturing PMI is the single most important leading indicator.",
        "Front-month roll cost affects futures-based back-test slightly.",
      ],
    },
  },
  {
    symbol: "WTI",
    name: "WTI Crude Oil",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "CL=F",
    searchTerms: ["WTI Crude", "WTI", "Crude Oil Futures"],
    widgetSymbol: "NYMEX:CL1!",
    priceScale: 100,
    price: 74.9,
    change24h: -0.8,
    activeStrategy: "RSI Pullback",
    score: 72,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 2.5,
    timeframe: "4H",
    riskScore: 43,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 50,
      winRatePct: 47.2,
      profitFactor: 1.72,
      maxDrawdownPct: -14.4,
      annualisedReturnPct: 12.4,
      sharpe: 0.88,
      warnings: [
        "OPEC+ meetings are binary risk events — avoid major positions around them.",
        "Geopolitical shocks (2022 Russia-Ukraine) created extreme intraday gaps.",
      ],
    },
  },
  {
    symbol: "NATGAS",
    name: "Natural Gas",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "NG=F",
    searchTerms: ["Natural Gas", "Natural Gas Futures"],
    widgetSymbol: "NYMEX:NG1!",
    priceScale: 1000,
    price: 2.84,
    change24h: 2.4,
    activeStrategy: "20-Day Breakout",
    score: 76,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.15,
    timeframe: "4H",
    riskScore: 47,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 42,
      winRatePct: 40.4,
      profitFactor: 1.64,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 10.4,
      sharpe: 0.72,
      warnings: [
        "Seasonal demand patterns create strong but regime-dependent signals.",
        "Winter storage data releases are major binary risk events.",
      ],
    },
  },
  {
    symbol: "DJI",
    name: "Dow Jones Industrial Average",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^DJI",
    searchTerms: ["Dow Jones", "DJI"],
    widgetSymbol: "TVC:DJI",
    priceScale: 100,
    price: 38940,
    change24h: 0.6,
    activeStrategy: "50/200 Trend",
    score: 79,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 312,
    timeframe: "1D",
    riskScore: 20,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 22,
      winRatePct: 54.4,
      profitFactor: 2.38,
      maxDrawdownPct: -7.4,
      annualisedReturnPct: 14.4,
      sharpe: 1.44,
      warnings: [
        "Price-weighted index gives outsentric influence to Boeing, Goldman, UNH.",
        "Trade via DIA ETF or CME YM1! futures for actual execution.",
      ],
    },
  },
  {
    symbol: "RUT",
    name: "Russell 2000",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^RUT",
    searchTerms: ["Russell 2000", "RUT"],
    widgetSymbol: "TVC:RUT",
    priceScale: 100,
    price: 2086,
    change24h: -0.5,
    activeStrategy: "RSI Pullback",
    score: 74,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 34,
    timeframe: "4H",
    riskScore: 29,
    tradeability: "WATCH",
    stance: "Short",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 56,
      winRatePct: 50.4,
      profitFactor: 1.84,
      maxDrawdownPct: -10.4,
      annualisedReturnPct: 12.4,
      sharpe: 1.08,
      warnings: [
        "Small-cap exposure means higher sensitivity to credit conditions and rate expectations.",
        "Trade via IWM ETF or CME RTY1! futures for actual execution.",
      ],
    },
  },
  {
    symbol: "FTSE",
    name: "FTSE 100",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^FTSE",
    searchTerms: ["FTSE 100", "FTSE"],
    widgetSymbol: "TVC:UKX",
    priceScale: 100,
    price: 8342,
    change24h: 0.3,
    activeStrategy: "50/200 Trend",
    score: 76,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 62,
    timeframe: "1D",
    riskScore: 19,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 22,
      winRatePct: 52.4,
      profitFactor: 2.04,
      maxDrawdownPct: -7.4,
      annualisedReturnPct: 10.4,
      sharpe: 1.18,
      warnings: [
        "GBP/USD fluctuations affect GBP-denominated returns vs USD-denominated analysis.",
        "Trade via ISF.L, spread bet UK100, or CME FTSE futures for actual execution.",
      ],
    },
  },
  {
    symbol: "DAX",
    name: "DAX Index",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^GDAXI",
    searchTerms: ["DAX", "Germany 40"],
    widgetSymbol: "XETR:DAX",
    priceScale: 100,
    price: 18620,
    change24h: 0.8,
    activeStrategy: "20-Day Breakout",
    score: 81,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 148,
    timeframe: "1D",
    riskScore: 23,
    tradeability: "TRADEABLE",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 38,
      winRatePct: 46.4,
      profitFactor: 2.04,
      maxDrawdownPct: -9.4,
      annualisedReturnPct: 14.4,
      sharpe: 1.24,
      warnings: [
        "European energy crisis (2022) and Russia-Ukraine war created macro overrides.",
        "Trade via EXS1.DE ETF, spread bet Germany 40, or Eurex FDAX futures.",
      ],
    },
  },
  {
    symbol: "HBAR",
    name: "Hedera",
    assetClass: "Crypto",
    marketDataSource: "coinbase",
    coingeckoCoinId: "hedera-hashgraph",
    searchTerms: ["Hedera", "HBAR"],
    widgetSymbol: "COINBASE:HBARUSD",
    priceScale: 100000,
    price: 0.116,
    change24h: 1.4,
    activeStrategy: "50/200 Trend",
    score: 72,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.006,
    timeframe: "1D",
    riskScore: 29,
    tradeability: "WATCH",
    stance: "Long",
    backtestStats: {
      period: "Jan 2021 – Jun 2026",
      totalTrades: 26,
      winRatePct: 47.4,
      profitFactor: 1.82,
      maxDrawdownPct: -22.4,
      annualisedReturnPct: 18.4,
      sharpe: 1.04,
      warnings: [
        "Enterprise adoption cycles are slower than retail crypto narrative.",
        "Governance council decisions create irregular supply events.",
      ],
    },
  },
];

export function getInstrumentUniverseEntry(symbol: string) {
  return instrumentUniverse.find((entry) => entry.symbol === symbol.toUpperCase()) ?? null;
}

/**
 * Returns a human-readable string telling a trader exactly where to find and
 * execute this instrument on real markets. The string is shown in the scanner
 * and asset-detail pages so there is never any ambiguity about which product
 * to use.
 */
export function getInstrumentTradeVia(entry: InstrumentUniverseEntry): string {
  const [exchange, ticker] = entry.widgetSymbol.split(":");

  // Proxy / composite instruments — point directly to the proxy ticker
  if (entry.proxyNote) {
    return `${exchange}: ${ticker} (listed proxy — search this ticker on your broker or TradingView)`;
  }

  if (entry.assetClass === "Crypto") {
    if (exchange === "COINBASE") {
      const pair = ticker.replace("USD", "/USD");
      const bybitPair = `${entry.symbol}/USDT`;
      return `Coinbase Advanced Trade: ${pair} · Bybit: ${bybitPair} · or any major crypto exchange`;
    }
    if (exchange === "BYBIT") {
      return `Bybit: ${ticker} · Binance: ${entry.symbol}/USDT · or any major crypto exchange`;
    }
    if (exchange === "KUCOIN") {
      return `KuCoin: ${ticker} · or any exchange listing ${entry.symbol}`;
    }
    return `${exchange}: ${ticker}`;
  }

  if (entry.assetClass === "Forex") {
    const pair = ticker; // e.g. EURUSD
    return `Any retail FX broker: ${pair} · Spread bet: ${pair} · FX futures on CME`;
  }

  if (entry.assetClass === "Equity") {
    const brokerNote = exchange === "NASDAQ"
      ? `NASDAQ: ${ticker} · IG / Spread Co: ${ticker} (US equity) · IBKR: ${ticker}`
      : `NYSE: ${ticker} · IG / Spread Co: ${ticker} (US equity) · IBKR: ${ticker}`;
    return brokerNote;
  }

  if (entry.assetClass === "ETF") {
    return `${exchange}: ${ticker} · IG: ${ticker} (US ETF) · IBKR: ${ticker}`;
  }

  if (entry.assetClass === "Index") {
    const futuresMap: Record<string, string> = {
      SPX: "CME: ES1! (E-mini S&P 500) · IG: Wall Street 500 · Spread bet: US500",
      NDX: "CME: NQ1! (E-mini Nasdaq) · IG: US Tech 100 · Spread bet: US100",
      DJI: "CME: YM1! (E-mini Dow) · IG: Wall Street 30 · DIA ETF (AMEX)",
      RUT: "CME: RTY1! (Russell 2000) · IG: US Small Cap 2000 · IWM ETF (AMEX)",
      FTSE: "ICE: Z1! (FTSE 100 futures) · IG: UK 100 · Spread bet: UK100 · ISF.L ETF",
      DAX: "Eurex: FDAX1! (DAX futures) · IG: Germany 40 · Spread bet: GER40 · EXS1.DE ETF",
    };
    return futuresMap[entry.symbol] ?? `${exchange}: ${ticker} · trade via your broker's index CFD`;
  }

  if (entry.assetClass === "Commodity") {
    const commodityMap: Record<string, string> = {
      GOLD: "COMEX: GC1! · IG: Gold · Spread bet: Gold · XAUUSD on FX platforms",
      SILVER: "COMEX: SI1! · IG: Silver · Spread bet: Silver · XAGUSD on FX platforms",
      WTI: "NYMEX: CL1! · IG: Oil (US Crude) · Spread bet: US Crude",
      BRENT: "ICE: B1! · IG: Oil (UK Brent) · Spread bet: UK Oil",
      COPPER: "COMEX: HG1! · IG: Copper · Spread bet: Copper",
      NATGAS: "NYMEX: NG1! · IG: Natural Gas · Spread bet: Natural Gas",
    };
    return commodityMap[entry.symbol] ?? `${exchange}: ${ticker} · trade via your broker's commodity CFD`;
  }

  return `${exchange}: ${ticker}`;
}

// ---------------------------------------------------------------------------
// Platform metadata + per-instrument platform list
// ---------------------------------------------------------------------------

export type PlatformKey =
  | "coinbase"
  | "bybit"
  | "binance"
  | "kraken"
  | "ig"
  | "ibkr"
  | "cme"
  | "oanda"
  | "etoro"
  | "spreadex"
  | "kucoin";

export const PLATFORM_META: Record<
  PlatformKey,
  { name: string; domain: string; url: string }
> = {
  coinbase:  { name: "Coinbase",  domain: "coinbase.com",              url: "https://advanced.coinbase.com" },
  bybit:     { name: "Bybit",     domain: "bybit.com",                 url: "https://www.bybit.com/trade/usdt" },
  binance:   { name: "Binance",   domain: "binance.com",               url: "https://www.binance.com/en/trade" },
  kraken:    { name: "Kraken",    domain: "kraken.com",                url: "https://www.kraken.com/prices" },
  kucoin:    { name: "KuCoin",    domain: "kucoin.com",                url: "https://www.kucoin.com/trade" },
  ig:        { name: "IG",        domain: "ig.com",                    url: "https://www.ig.com/uk/trading-platforms" },
  ibkr:      { name: "IBKR",      domain: "interactivebrokers.com",    url: "https://www.interactivebrokers.com/en/trading/trading.php" },
  cme:       { name: "CME",       domain: "cmegroup.com",              url: "https://www.cmegroup.com/markets" },
  oanda:     { name: "OANDA",     domain: "oanda.com",                 url: "https://www.oanda.com/gb-en/trading" },
  etoro:     { name: "eToro",     domain: "etoro.com",                 url: "https://www.etoro.com" },
  spreadex:  { name: "Spreadex",  domain: "spreadex.com",              url: "https://www.spreadex.com/markets" },
};

/**
 * Returns the 2–3 best execution venues for this instrument in priority order.
 * Used to render platform logo chips in the scanner and asset pages.
 */
export function getInstrumentPlatforms(entry: InstrumentUniverseEntry): PlatformKey[] {
  if (entry.assetClass === "Crypto") {
    const [exchange] = entry.widgetSymbol.split(":");
    if (exchange === "COINBASE") return ["coinbase", "bybit", "binance"];
    if (exchange === "KRAKEN")   return ["kraken",   "bybit", "binance"];
    if (exchange === "KUCOIN")   return ["kucoin",   "bybit", "binance"];
    return ["bybit", "binance", "coinbase"];
  }
  if (entry.assetClass === "Forex")     return ["ig",   "oanda", "ibkr"];
  if (entry.assetClass === "Equity")    return ["ibkr", "ig",    "etoro"];
  if (entry.assetClass === "ETF")       return ["ibkr", "ig"];
  if (entry.assetClass === "Index")     return ["ig",   "spreadex", "cme"];
  if (entry.assetClass === "Commodity") return ["ig",   "cme",      "ibkr"];
  return ["ibkr", "ig"];
}

export function buildInstrumentSparkline(entry: InstrumentUniverseEntry) {
  const momentumBoost = Math.round(entry.change24h * 0.8);
  const qualityBias = Math.round((entry.score - 70) / 4);
  const direction = entry.stance === "Short" ? -1 : 1;
  const start = 18 + Math.max(-4, Math.min(4, qualityBias));
  const series = Array.from({ length: 12 }, (_, index) => {
    const wave = (index % 3) - 1;
    const drift = Math.round(index * 0.9 * direction);
    const momentum = Math.round((index / 11) * momentumBoost);
    return start + drift + momentum + wave;
  });

  return direction === -1 ? [...series].reverse() : series;
}

export function buildInstrumentForecast(entry: InstrumentUniverseEntry) {
  if (entry.stance === "Short") {
    return `${entry.symbol} looks vulnerable unless price quickly reclaims the short-term trend shelf.`;
  }

  if (entry.change24h >= 3) {
    return `${entry.symbol} is pressing higher with constructive short-term momentum and clean continuation potential.`;
  }

  return `${entry.symbol} is constructive, but the better outcome still comes from patient entries rather than chasing price.`;
}

export function buildInstrumentAiBias(entry: InstrumentUniverseEntry) {
  if (entry.stance === "Short") {
    return "The tape is weakening enough that fade setups are more attractive than early dip-buying.";
  }

  if (entry.volatility === "Fast") {
    return "Momentum is strong, but size should respect a faster ATR profile.";
  }

  return "Trend structure is supportive and the tape is orderly enough for a measured plan.";
}

