export type InstrumentAssetClass =
  | "Crypto"
  | "ETF"
  | "Equity"
  | "Forex"
  | "Commodity"
  | "Index";

export type InstrumentStrategy =
  | "20-Day Breakout"
  | "50/200 Trend"
  | "RSI Pullback";

export type InstrumentLiquidity = "High" | "Moderate" | "Thin";
export type InstrumentVolatility = "Contained" | "Elevated" | "Fast";
export type InstrumentTradeability = "TRADEABLE" | "WATCH" | "BLOCKED";
export type InstrumentStance = "Long" | "Short";
export type InstrumentMarketDataSource = "coingecko" | "yahoo";

export type InstrumentUniverseEntry = {
  symbol: string;
  name: string;
  assetClass: InstrumentAssetClass;
  marketDataSource: InstrumentMarketDataSource;
  coingeckoCoinId?: string;
  yahooSymbol?: string;
  searchTerms: string[];
  widgetSymbol: string;
  priceScale: number;
  proxyNote?: string;
  price: number;
  change24h: number;
  activeStrategy: InstrumentStrategy;
  score: number;
  tradeable: boolean;
  liquidity: InstrumentLiquidity;
  volatility: InstrumentVolatility;
  atr: number;
  timeframe: "4H" | "1D";
  riskScore: number;
  tradeability: InstrumentTradeability;
  stance: InstrumentStance;
};

export const instrumentUniverse: InstrumentUniverseEntry[] = [
  {
    symbol: "LINK",
    name: "Chainlink",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "chainlink",
    searchTerms: ["Chainlink", "LINK"],
    widgetSymbol: "COINBASE:LINKUSD",
    priceScale: 100,
    price: 18.42,
    change24h: 4.7,
    activeStrategy: "20-Day Breakout",
    score: 91,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.84,
    timeframe: "1D",
    riskScore: 29,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "ONDO",
    name: "Ondo",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "ondo-finance",
    searchTerms: ["Ondo", "ONDO"],
    widgetSymbol: "BYBIT:ONDOUSDT",
    priceScale: 10000,
    price: 1.28,
    change24h: 2.1,
    activeStrategy: "RSI Pullback",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.07,
    timeframe: "4H",
    riskScore: 42,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "RENDER",
    name: "Render",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "render-token",
    searchTerms: ["Render", "RENDER"],
    widgetSymbol: "COINBASE:RENDERUSD",
    priceScale: 100,
    price: 10.86,
    change24h: 6.4,
    activeStrategy: "20-Day Breakout",
    score: 94,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.63,
    timeframe: "4H",
    riskScore: 34,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "AKT",
    name: "Akash Network",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "akash-network",
    searchTerms: ["Akash Network", "AKT"],
    widgetSymbol: "KUCOIN:AKTUSDT",
    priceScale: 100,
    price: 4.19,
    change24h: -0.8,
    activeStrategy: "RSI Pullback",
    score: 72,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Elevated",
    atr: 0.29,
    timeframe: "4H",
    riskScore: 53,
    tradeability: "BLOCKED",
    stance: "Long",
  },
  {
    symbol: "AINF",
    name: "AI Infrastructure Index",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "AIQ",
    searchTerms: ["AIQ", "AIQ ETF"],
    widgetSymbol: "AMEX:AIQ",
    priceScale: 100,
    proxyNote:
      "Using AIQ as a liquid listed proxy for the internal AI Infrastructure Index composite.",
    price: 42.38,
    change24h: 1.2,
    activeStrategy: "50/200 Trend",
    score: 79,
    tradeable: true,
    liquidity: "Moderate",
    volatility: "Contained",
    atr: 1.78,
    timeframe: "1D",
    riskScore: 26,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "NUKZ",
    name: "Nuclear Energy Index",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "NLR",
    searchTerms: ["NLR", "NLR ETF"],
    widgetSymbol: "AMEX:NLR",
    priceScale: 100,
    proxyNote:
      "Using NLR as a liquid listed proxy for the internal Nuclear Energy Index composite.",
    price: 33.71,
    change24h: -1.1,
    activeStrategy: "20-Day Breakout",
    score: 66,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Contained",
    atr: 1.12,
    timeframe: "1D",
    riskScore: 48,
    tradeability: "BLOCKED",
    stance: "Long",
  },
  {
    symbol: "URA",
    name: "Global X Uranium ETF",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "URA",
    searchTerms: ["URA", "Global X Uranium ETF"],
    widgetSymbol: "AMEX:URA",
    priceScale: 100,
    price: 37.94,
    change24h: 0.6,
    activeStrategy: "20-Day Breakout",
    score: 76,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 1.22,
    timeframe: "1D",
    riskScore: 33,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "TKNX",
    name: "Tokenisation Leaders ETF",
    assetClass: "ETF",
    marketDataSource: "yahoo",
    yahooSymbol: "BLOK",
    searchTerms: ["BLOK", "Amplify Transformational Data Sharing ETF"],
    widgetSymbol: "AMEX:BLOK",
    priceScale: 100,
    proxyNote:
      "Using BLOK as a liquid listed proxy for the internal Tokenisation Leaders ETF composite.",
    price: 28.14,
    change24h: 3.3,
    activeStrategy: "50/200 Trend",
    score: 88,
    tradeable: true,
    liquidity: "Moderate",
    volatility: "Contained",
    atr: 1.04,
    timeframe: "1D",
    riskScore: 31,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "bitcoin",
    searchTerms: ["Bitcoin", "BTC"],
    widgetSymbol: "COINBASE:BTCUSD",
    priceScale: 100,
    price: 108420,
    change24h: 2.6,
    activeStrategy: "50/200 Trend",
    score: 93,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 3560,
    timeframe: "1D",
    riskScore: 28,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "ethereum",
    searchTerms: ["Ethereum", "ETH"],
    widgetSymbol: "COINBASE:ETHUSD",
    priceScale: 100,
    price: 5342,
    change24h: 3.1,
    activeStrategy: "20-Day Breakout",
    score: 90,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 214,
    timeframe: "1D",
    riskScore: 33,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "SOL",
    name: "Solana",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "solana",
    searchTerms: ["Solana", "SOL"],
    widgetSymbol: "COINBASE:SOLUSD",
    priceScale: 100,
    price: 228.4,
    change24h: 4.8,
    activeStrategy: "RSI Pullback",
    score: 89,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 12.6,
    timeframe: "4H",
    riskScore: 39,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "EURUSD",
    name: "Euro / US Dollar",
    assetClass: "Forex",
    marketDataSource: "yahoo",
    yahooSymbol: "EURUSD=X",
    searchTerms: ["EURUSD", "Euro Dollar"],
    widgetSymbol: "FX:EURUSD",
    priceScale: 100000,
    price: 1.0864,
    change24h: 0.4,
    activeStrategy: "RSI Pullback",
    score: 83,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.0062,
    timeframe: "4H",
    riskScore: 24,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "GBPUSD",
    name: "British Pound / US Dollar",
    assetClass: "Forex",
    marketDataSource: "yahoo",
    yahooSymbol: "GBPUSD=X",
    searchTerms: ["GBPUSD", "Pound Dollar"],
    widgetSymbol: "FX:GBPUSD",
    priceScale: 100000,
    price: 1.2748,
    change24h: 0.2,
    activeStrategy: "50/200 Trend",
    score: 80,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.0084,
    timeframe: "1D",
    riskScore: 22,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "GOLD",
    name: "Spot Gold",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "GC=F",
    searchTerms: ["Gold", "Gold Futures"],
    widgetSymbol: "COMEX:GC1!",
    priceScale: 10,
    proxyNote:
      "Using front-month COMEX gold futures as a liquid listed proxy for the internal spot gold view.",
    price: 2384.5,
    change24h: 0.9,
    activeStrategy: "20-Day Breakout",
    score: 87,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 32.4,
    timeframe: "1D",
    riskScore: 27,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "SILVER",
    name: "Spot Silver",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "SI=F",
    searchTerms: ["Silver", "Silver Futures"],
    widgetSymbol: "COMEX:SI1!",
    priceScale: 100,
    proxyNote:
      "Using front-month COMEX silver futures as a liquid listed proxy for the internal spot silver view.",
    price: 31.84,
    change24h: 1.7,
    activeStrategy: "20-Day Breakout",
    score: 82,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.96,
    timeframe: "1D",
    riskScore: 35,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "BRENT",
    name: "Brent Crude",
    assetClass: "Commodity",
    marketDataSource: "yahoo",
    yahooSymbol: "BZ=F",
    searchTerms: ["Brent Crude", "Brent Futures"],
    widgetSymbol: "TVC:UKOIL",
    priceScale: 100,
    price: 78.2,
    change24h: -0.6,
    activeStrategy: "RSI Pullback",
    score: 74,
    tradeable: false,
    liquidity: "High",
    volatility: "Elevated",
    atr: 2.8,
    timeframe: "4H",
    riskScore: 44,
    tradeability: "BLOCKED",
    stance: "Long",
  },
  {
    symbol: "SPX",
    name: "S&P 500 Index",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^GSPC",
    searchTerms: ["S&P 500", "SPX"],
    widgetSymbol: "SP:SPX",
    priceScale: 100,
    price: 5340.18,
    change24h: 0.7,
    activeStrategy: "50/200 Trend",
    score: 85,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 76.4,
    timeframe: "1D",
    riskScore: 21,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "NDX",
    name: "Nasdaq 100 Index",
    assetClass: "Index",
    marketDataSource: "yahoo",
    yahooSymbol: "^NDX",
    searchTerms: ["Nasdaq 100", "NDX"],
    widgetSymbol: "NASDAQ:NDX",
    priceScale: 100,
    price: 19284.62,
    change24h: 1.1,
    activeStrategy: "50/200 Trend",
    score: 88,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 248.5,
    timeframe: "1D",
    riskScore: 24,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "NVDA",
    searchTerms: ["NVIDIA", "NVDA"],
    widgetSymbol: "NASDAQ:NVDA",
    priceScale: 100,
    price: 154.62,
    change24h: 2.9,
    activeStrategy: "20-Day Breakout",
    score: 92,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 6.8,
    timeframe: "1D",
    riskScore: 32,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    assetClass: "Equity",
    marketDataSource: "yahoo",
    yahooSymbol: "MSFT",
    searchTerms: ["Microsoft", "MSFT"],
    widgetSymbol: "NASDAQ:MSFT",
    priceScale: 100,
    price: 512.48,
    change24h: 1.4,
    activeStrategy: "50/200 Trend",
    score: 86,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 9.4,
    timeframe: "1D",
    riskScore: 23,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "AVAX",
    name: "Avalanche",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "avalanche-2",
    searchTerms: ["Avalanche", "AVAX"],
    widgetSymbol: "COINBASE:AVAXUSD",
    priceScale: 100,
    price: 41.26,
    change24h: 3.8,
    activeStrategy: "20-Day Breakout",
    score: 89,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 2.2,
    timeframe: "4H",
    riskScore: 37,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "XRP",
    name: "XRP",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "ripple",
    searchTerms: ["XRP", "Ripple"],
    widgetSymbol: "COINBASE:XRPUSD",
    priceScale: 10000,
    price: 0.71,
    change24h: 1.9,
    activeStrategy: "50/200 Trend",
    score: 81,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.03,
    timeframe: "1D",
    riskScore: 26,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "DOGE",
    name: "Dogecoin",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "dogecoin",
    searchTerms: ["Dogecoin", "DOGE"],
    widgetSymbol: "COINBASE:DOGEUSD",
    priceScale: 100000,
    price: 0.214,
    change24h: -1.7,
    activeStrategy: "RSI Pullback",
    score: 75,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.012,
    timeframe: "4H",
    riskScore: 46,
    tradeability: "WATCH",
    stance: "Short",
  },
  {
    symbol: "ADA",
    name: "Cardano",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "cardano",
    searchTerms: ["Cardano", "ADA"],
    widgetSymbol: "COINBASE:ADAUSD",
    priceScale: 10000,
    price: 0.58,
    change24h: -0.9,
    activeStrategy: "50/200 Trend",
    score: 73,
    tradeable: false,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.026,
    timeframe: "1D",
    riskScore: 49,
    tradeability: "BLOCKED",
    stance: "Short",
  },
  {
    symbol: "BNB",
    name: "BNB",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "binancecoin",
    searchTerms: ["BNB", "Binance Coin"],
    widgetSymbol: "BYBIT:BNBUSDT",
    priceScale: 100,
    price: 662.4,
    change24h: 2.2,
    activeStrategy: "50/200 Trend",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 18.6,
    timeframe: "1D",
    riskScore: 25,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "LTC",
    name: "Litecoin",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "litecoin",
    searchTerms: ["Litecoin", "LTC"],
    widgetSymbol: "COINBASE:LTCUSD",
    priceScale: 100,
    price: 92.3,
    change24h: 0.8,
    activeStrategy: "RSI Pullback",
    score: 70,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 3.9,
    timeframe: "4H",
    riskScore: 35,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "DOT",
    name: "Polkadot",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "polkadot",
    searchTerms: ["Polkadot", "DOT"],
    widgetSymbol: "COINBASE:DOTUSD",
    priceScale: 100,
    price: 8.14,
    change24h: -2.1,
    activeStrategy: "20-Day Breakout",
    score: 68,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Elevated",
    atr: 0.41,
    timeframe: "1D",
    riskScore: 52,
    tradeability: "BLOCKED",
    stance: "Short",
  },
  {
    symbol: "UNI",
    name: "Uniswap",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "uniswap",
    searchTerms: ["Uniswap", "UNI"],
    widgetSymbol: "COINBASE:UNIUSD",
    priceScale: 100,
    price: 11.18,
    change24h: 2.4,
    activeStrategy: "RSI Pullback",
    score: 79,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.58,
    timeframe: "4H",
    riskScore: 38,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "AAVE",
    name: "Aave",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "aave",
    searchTerms: ["Aave", "AAVE"],
    widgetSymbol: "COINBASE:AAVEUSD",
    priceScale: 100,
    price: 118.5,
    change24h: 3.4,
    activeStrategy: "20-Day Breakout",
    score: 83,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 5.4,
    timeframe: "4H",
    riskScore: 39,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "MKR",
    name: "Maker",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "maker",
    searchTerms: ["Maker", "MKR"],
    widgetSymbol: "COINBASE:MKRUSD",
    priceScale: 100,
    price: 2875,
    change24h: -1.4,
    activeStrategy: "50/200 Trend",
    score: 77,
    tradeable: true,
    liquidity: "Moderate",
    volatility: "Elevated",
    atr: 122,
    timeframe: "1D",
    riskScore: 41,
    tradeability: "WATCH",
    stance: "Short",
  },
  {
    symbol: "ARB",
    name: "Arbitrum",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "arbitrum",
    searchTerms: ["Arbitrum", "ARB"],
    widgetSymbol: "COINBASE:ARBUSD",
    priceScale: 10000,
    price: 1.06,
    change24h: 4.1,
    activeStrategy: "20-Day Breakout",
    score: 82,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.05,
    timeframe: "4H",
    riskScore: 37,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "INJ",
    name: "Injective",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "injective-protocol",
    searchTerms: ["Injective", "INJ"],
    widgetSymbol: "BYBIT:INJUSDT",
    priceScale: 100,
    price: 29.6,
    change24h: -1.2,
    activeStrategy: "RSI Pullback",
    score: 78,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 1.7,
    timeframe: "4H",
    riskScore: 44,
    tradeability: "WATCH",
    stance: "Short",
  },
  {
    symbol: "ATOM",
    name: "Cosmos",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "cosmos",
    searchTerms: ["Cosmos", "ATOM"],
    widgetSymbol: "COINBASE:ATOMUSD",
    priceScale: 100,
    price: 9.34,
    change24h: 1.1,
    activeStrategy: "50/200 Trend",
    score: 76,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.44,
    timeframe: "1D",
    riskScore: 31,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "TIA",
    name: "Celestia",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "celestia",
    searchTerms: ["Celestia", "TIA"],
    widgetSymbol: "BYBIT:TIAUSDT",
    priceScale: 100,
    price: 10.84,
    change24h: 5.2,
    activeStrategy: "20-Day Breakout",
    score: 88,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.68,
    timeframe: "4H",
    riskScore: 40,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "APT",
    name: "Aptos",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "aptos",
    searchTerms: ["Aptos", "APT"],
    widgetSymbol: "BYBIT:APTUSDT",
    priceScale: 100,
    price: 12.46,
    change24h: 2.8,
    activeStrategy: "50/200 Trend",
    score: 80,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.61,
    timeframe: "1D",
    riskScore: 34,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "OP",
    name: "Optimism",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "optimism",
    searchTerms: ["Optimism", "OP"],
    widgetSymbol: "COINBASE:OPUSD",
    priceScale: 10000,
    price: 2.94,
    change24h: -1.9,
    activeStrategy: "RSI Pullback",
    score: 74,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.16,
    timeframe: "4H",
    riskScore: 45,
    tradeability: "WATCH",
    stance: "Short",
  },
  {
    symbol: "FIL",
    name: "Filecoin",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "filecoin",
    searchTerms: ["Filecoin", "FIL"],
    widgetSymbol: "COINBASE:FILUSD",
    priceScale: 100,
    price: 6.82,
    change24h: 1.5,
    activeStrategy: "50/200 Trend",
    score: 72,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.29,
    timeframe: "1D",
    riskScore: 30,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "ICP",
    name: "Internet Computer",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "internet-computer",
    searchTerms: ["Internet Computer", "ICP"],
    widgetSymbol: "COINBASE:ICPUSD",
    priceScale: 100,
    price: 13.72,
    change24h: 2.7,
    activeStrategy: "20-Day Breakout",
    score: 79,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.72,
    timeframe: "4H",
    riskScore: 38,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "XLM",
    name: "Stellar",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "stellar",
    searchTerms: ["Stellar", "XLM"],
    widgetSymbol: "COINBASE:XLMUSD",
    priceScale: 100000,
    price: 0.136,
    change24h: -0.7,
    activeStrategy: "RSI Pullback",
    score: 67,
    tradeable: false,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.006,
    timeframe: "4H",
    riskScore: 50,
    tradeability: "BLOCKED",
    stance: "Short",
  },
  {
    symbol: "TRX",
    name: "TRON",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "tron",
    searchTerms: ["TRON", "TRX"],
    widgetSymbol: "BYBIT:TRXUSDT",
    priceScale: 100000,
    price: 0.128,
    change24h: 1.2,
    activeStrategy: "50/200 Trend",
    score: 73,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.004,
    timeframe: "1D",
    riskScore: 28,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "ETC",
    name: "Ethereum Classic",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "ethereum-classic",
    searchTerms: ["Ethereum Classic", "ETC"],
    widgetSymbol: "COINBASE:ETCUSD",
    priceScale: 100,
    price: 32.4,
    change24h: -2.4,
    activeStrategy: "20-Day Breakout",
    score: 69,
    tradeable: false,
    liquidity: "Moderate",
    volatility: "Fast",
    atr: 1.8,
    timeframe: "1D",
    riskScore: 55,
    tradeability: "BLOCKED",
    stance: "Short",
  },
  {
    symbol: "BCH",
    name: "Bitcoin Cash",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "bitcoin-cash",
    searchTerms: ["Bitcoin Cash", "BCH"],
    widgetSymbol: "COINBASE:BCHUSD",
    priceScale: 100,
    price: 486.3,
    change24h: 2.9,
    activeStrategy: "20-Day Breakout",
    score: 80,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 21.4,
    timeframe: "4H",
    riskScore: 38,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "PEPE",
    name: "Pepe",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "pepe",
    searchTerms: ["Pepe", "PEPE"],
    widgetSymbol: "BYBIT:PEPEUSDT",
    priceScale: 100000000,
    price: 0.0000142,
    change24h: 6.8,
    activeStrategy: "20-Day Breakout",
    score: 85,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.0000008,
    timeframe: "4H",
    riskScore: 47,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "SUI",
    name: "Sui",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "sui",
    searchTerms: ["Sui", "SUI"],
    widgetSymbol: "BYBIT:SUIUSDT",
    priceScale: 10000,
    price: 1.62,
    change24h: 4.5,
    activeStrategy: "50/200 Trend",
    score: 87,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.08,
    timeframe: "4H",
    riskScore: 36,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "NEAR",
    name: "NEAR Protocol",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "near",
    searchTerms: ["NEAR Protocol", "NEAR"],
    widgetSymbol: "BYBIT:NEARUSDT",
    priceScale: 100,
    price: 7.92,
    change24h: 3.7,
    activeStrategy: "50/200 Trend",
    score: 84,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.42,
    timeframe: "4H",
    riskScore: 34,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "SEI",
    name: "Sei",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "sei-network",
    searchTerms: ["Sei", "SEI"],
    widgetSymbol: "BYBIT:SEIUSDT",
    priceScale: 10000,
    price: 0.63,
    change24h: -1.5,
    activeStrategy: "RSI Pullback",
    score: 71,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.035,
    timeframe: "4H",
    riskScore: 46,
    tradeability: "WATCH",
    stance: "Short",
  },
  {
    symbol: "JUP",
    name: "Jupiter",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "jupiter-exchange-solana",
    searchTerms: ["Jupiter", "JUP"],
    widgetSymbol: "BYBIT:JUPUSDT",
    priceScale: 10000,
    price: 1.14,
    change24h: 5.1,
    activeStrategy: "20-Day Breakout",
    score: 86,
    tradeable: true,
    liquidity: "High",
    volatility: "Fast",
    atr: 0.06,
    timeframe: "4H",
    riskScore: 39,
    tradeability: "TRADEABLE",
    stance: "Long",
  },
  {
    symbol: "ENA",
    name: "Ethena",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "ethena",
    searchTerms: ["Ethena", "ENA"],
    widgetSymbol: "BYBIT:ENAUSDT",
    priceScale: 10000,
    price: 0.92,
    change24h: 2.6,
    activeStrategy: "RSI Pullback",
    score: 78,
    tradeable: true,
    liquidity: "High",
    volatility: "Elevated",
    atr: 0.045,
    timeframe: "4H",
    riskScore: 40,
    tradeability: "WATCH",
    stance: "Long",
  },
  {
    symbol: "ALGO",
    name: "Algorand",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "algorand",
    searchTerms: ["Algorand", "ALGO"],
    widgetSymbol: "COINBASE:ALGOUSD",
    priceScale: 100000,
    price: 0.188,
    change24h: -0.6,
    activeStrategy: "50/200 Trend",
    score: 66,
    tradeable: false,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.009,
    timeframe: "1D",
    riskScore: 48,
    tradeability: "BLOCKED",
    stance: "Short",
  },
  {
    symbol: "HBAR",
    name: "Hedera",
    assetClass: "Crypto",
    marketDataSource: "coingecko",
    coingeckoCoinId: "hedera-hashgraph",
    searchTerms: ["Hedera", "HBAR"],
    widgetSymbol: "COINBASE:HBARUSD",
    priceScale: 100000,
    price: 0.116,
    change24h: 1.4,
    activeStrategy: "50/200 Trend",
    score: 72,
    tradeable: true,
    liquidity: "High",
    volatility: "Contained",
    atr: 0.006,
    timeframe: "1D",
    riskScore: 29,
    tradeability: "WATCH",
    stance: "Long",
  },
];

export function getInstrumentUniverseEntry(symbol: string) {
  return instrumentUniverse.find((entry) => entry.symbol === symbol.toUpperCase()) ?? null;
}

export function buildInstrumentSparkline(entry: InstrumentUniverseEntry) {
  const momentumBoost = Math.round(entry.change24h * 0.8);
  const qualityBias = Math.round((entry.score - 70) / 4);
  const direction = entry.stance === "Short" ? -1 : 1;
  const start = 18 + Math.max(-4, Math.min(4, qualityBias));
  const series = Array.from({ length: 12 }, (_, index) => {
    const wave = (index % 3) - 1;
    const drift = Math.round(index * 0.9 * direction);
    const momentum = Math.round((index / 11) * momentumBoost);
    return start + drift + momentum + wave;
  });

  return direction === -1 ? [...series].reverse() : series;
}

export function buildInstrumentForecast(entry: InstrumentUniverseEntry) {
  if (entry.stance === "Short") {
    return `${entry.symbol} looks vulnerable unless price quickly reclaims the short-term trend shelf.`;
  }

  if (entry.change24h >= 3) {
    return `${entry.symbol} is pressing higher with constructive short-term momentum and clean continuation potential.`;
  }

  return `${entry.symbol} is constructive, but the better outcome still comes from patient entries rather than chasing price.`;
}

export function buildInstrumentAiBias(entry: InstrumentUniverseEntry) {
  if (entry.stance === "Short") {
    return "The tape is weakening enough that fade setups are more attractive than early dip-buying.";
  }

  if (entry.volatility === "Fast") {
    return "Momentum is strong, but size should respect a faster ATR profile.";
  }

  return "Trend structure is supportive and the tape is orderly enough for a measured plan.";
}
